import math
import collections
from collections import Counter
import re
from tqdm import tqdm

# Advent of Code[About][Events][Shop][Settings][Log Out]Krish (AoC++) 14*
#        λy.2024[Calendar][AoC++][Sponsors][Leaderboard][Stats]
# Our sponsors help make Advent of Code possible:
# Architus - Join us to build cool tech (and help elves) in Lithuania!
# --- Day 8: Resonant Collinearity ---
# You find yourselves on the roof of a top-secret Easter Bunny installation.

# While The Historians do their thing, you take a look at the familiar huge antenna. Much to your surprise, it seems to have been reconfigured to emit a signal that makes people 0.1% more likely to buy Easter Bunny brand Imitation Mediocre Chocolate as a Christmas gift! Unthinkable!

# Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific frequency indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:

# ............
# ........0...
# .....0......
# .......0....
# ....0.......
# ......A.....
# ............
# ............
# ........A...
# .........A..
# ............
# ............
# The signal only applies its nefarious effect at specific antinodes based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

# So, for these two antennas with frequency a, they create the two antinodes marked with #:

# ..........
# ...#......
# ..........
# ....a.....
# ..........
# .....a....
# ..........
# ......#...
# ..........
# ..........
# Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

# ..........
# ...#......
# #.........
# ....a.....
# ........a.
# .....a....
# ..#.......
# ......#...
# ..........
# ..........
# Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

# ..........
# ...#......
# #.........
# ....a.....
# ........a.
# .....a....
# ..#.......
# ......A...
# ..........
# ..........
# The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

# ......#....#
# ...#....0...
# ....#0....#.
# ..#....0....
# ....0....#..
# .#....A.....
# ...#........
# #......#....
# ........A...
# .........A..
# ..........#.
# ..........#.
# Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

# Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?

# To begin, get your puzzle input.

# Answer:


# You can also [Share] this puzzle.

TEST = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

PROD = """
.E..........m..0N.........f.......................
........N........P0...............................
.......j..................................F.......
........1j............P........................C..
...........................3..K......f..........E.
...........V...y...0.....................F........
1.......j.....P....y.N.......................F....
....................m...................C.........
..L......P....p..................w.m..............
............E......p..AU........8......f..........
..............C...............w....d..............
j1...............E..........3.........f........w..
.................p...A..........3.................
.................3..p........KU...w..r..F.........
7.........y........8.......................r......
........y..u......K...............................
...1..................8....C...K..................
...........h.......................6..............
......................U.........A.r..t........6...
...........5.........8..c.........................
.................U................t...............
.....L...O...................t.............d......
.........7........................................
......L..H...c.....9....t.................6.......
...........................c.M..................4.
.....R..7...O.....................................
.......................9......................d...
..................................................
.........L..9...R..........................6c.....
..M.....T.5.................................d.....
.......5OR...................T....................
.......D......o.........v...................r.....
...u....o.........5...............................
.......WR.....Y...........................e...4...
T............O......M..................4..a.......
.Y...................M............................
........W..D...............oh............e........
.......7......Do...................A...e.......4..
.W...Y..D........................h...v..........e.
..........V.....9.l.......h.......a.........n..v..
.......................H.....a2...................
..................................................
...V............Y....J..H2................vn......
..............................H2.................n
................V..........l...........k..........
.T..u........................J...ak...............
..................J.....l.........................
.................l................................
......u.........................................n.
......................J..k............2...........
"""

TEST2 = """
..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........
"""

TEST3 = """
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
"""

from pprint import pprint

x = TEST
x = PROD
x = x.strip()

# Data in differnt formats for quick access
text = x
lines = x.split("\n")
grid = [list(line) for line in lines]

result = 0

rows = len(grid)
cols = len(grid[0])

antinodes = set()
frequencies = {}

for i in range(rows):
    for j in range(cols):
        if grid[i][j] == ".":
            continue
        freq = grid[i][j]
        if freq not in frequencies:
            frequencies[freq] = []
        frequencies[freq].append((i, j))

pprint(frequencies)

for key in frequencies:
    for i in range(len(frequencies[key])):
        for j in range(i + 1, len(frequencies[key])):
            x1, y1 = frequencies[key][i]
            x2, y2 = frequencies[key][j]

            dx = x2 - x1
            dy = y2 - y1

            x3, y3 = x2, y2
            x4, y4 = x1, y1

            while True:
                added = False
                x3, y3 = x3 + dx, y3 + dy
                x4, y4 = x4 - dx, y4 - dy

                if 0 <= x3 < rows and 0 <= y3 < cols:
                    added = True
                    result += 1
                    antinodes.add((x3, y3))
                if 0 <= x4 < rows and 0 <= y4 < cols:
                    added = True
                    result += 1
                    antinodes.add((x4, y4))

                if not added:
                    break


for key in frequencies:
    for x, y in frequencies[key]:
        antinodes.add((x, y))


# make the grid again
new_grid = [["." for _ in range(cols)] for _ in range(rows)]

for x, y in antinodes:
    new_grid[x][y] = "#"

for key in frequencies:
    for x, y in frequencies[key]:
        new_grid[x][y] = key

for line in new_grid:
    print("".join(line))


# print(len(antinodes))
print(*list(sorted(antinodes)), sep="\n")
# print(result)
